#define MANIFEST                24
#define IDD_OPTIONS             1100
#define IDC_ARGS                1101
#define IDC_CMDLINE_LABEL       1102
#define IDD_ABOUT               1200
#define IDC_TSVERSION           1201
#define IDC_TSCOPYRIGHT         1202
#define IDC_TSWWWLINK           1203
#define IDC_TSLVERSION          1204
#define IDC_TSLCOPYRIGHT        1205
#define IDC_TSLWWWLINK          1206
#define IDR_FORMMENU            10000
#define IDM_AUTOSTART           10001
#define IDM_ABOUT               10002
#define IDR_TRAYMENU            11000
#define TSLOGO_ICON                100
#define TSSTOP_ICON           101
#define CGRN_ICON             102
#define CRED_ICON               103
#define STR_NEED_TORSERVER32    1
#define STR_NEED_TORSERVER64    2
#define STR_CANCEL              3
#define STR_OPTIONS             4
#define STR_TSARGS              5
#define STR_ABOUT               6
#define STR_RESETTETTINGS       7
#define STR_WORKING             8
#define STR_STOPPED             9
#define STR_STARTING            10
#define IDR_ACCEL1              1
#define IDM_OPTIONS             10003
#define IDR_XPMANIFEST1         1
